### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by ekoeryanto** [mkeen/rxcouch#15]
implement jwt authentication will be great.

**Comment by mkeen** [comment]
@ekoeryanto I added JWT support in npm release `4.8.0` 😀

Commits:
- https://github.com/mkeen/rxcouch/commit/07865158ae81e6a6bb284a3aa38ea431c38f3c52
- https://github.com/mkeen/rxcouch/commit/2daf9300a55f2b6dd42a9f9046c56d4a7c5cac8c

**Comment by ekoeryanto** [comment]
Yeay!

going to take a look, asap.
